import Foundation

/// Manager for Info.plist related configurations
///
/// This file serves as documentation for all the Info.plist settings that are
/// auto-generated by the build system. No actual code is executed from this file.
/// All keys are set in the Xcode build settings or defined in Amped-Info.plist.
///
/// Key Info.plist configurations:
/// - NSHealthShareUsageDescription: Required for reading HealthKit data (from Amped-Info.plist)
/// - NSHealthUpdateUsageDescription: Required for updating HealthKit data (from Amped-Info.plist)
/// - UIApplicationSceneManifest: Generated automatically by Xcode
/// - UIApplicationSupportsIndirectInputEvents: Set to YES
/// - UILaunchScreen: Generated automatically
/// - UISupportedInterfaceOrientations: Portrait and landscape orientations
struct InfoPlistManager {
    
    /// List of keys required for HealthKit integration
    /// Note: These are already defined in Amped-Info.plist
    static let healthKitKeys = [
        "NSHealthShareUsageDescription": "Amped needs access to your health data to calculate personalized life impact metrics.",
        "NSHealthUpdateUsageDescription": "Amped needs permission to access your health data to provide accurate lifespan projections."
    ]
    
    /// List of UI related keys
    static let uiKeys = [
        "UIApplicationSceneManifest_Generation": "YES",
        "UIApplicationSupportsIndirectInputEvents": "YES",
        "UILaunchScreen_Generation": "YES"
    ]
    
    /// List of supported interface orientations
    static let supportedOrientations = [
        "iPhone": ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"],
        "iPad": ["UIInterfaceOrientationPortrait", "UIInterfaceOrientationPortraitUpsideDown", "UIInterfaceOrientationLandscapeLeft", "UIInterfaceOrientationLandscapeRight"]
    ]
} 