Text("Power Your Battery")
Text("Access your health data to calculate and maximize your life battery")
Text("Core Health Metrics")
Text("We need these key metrics to power your experience:")
Text("Steps")
Text("Daily activity level - powers your movement score")
Text("Exercise Minutes")
Text("Workout intensity - boosts your energy levels")
Text("Sleep")
Text("Rest quality - recharges your daily battery")
Text("Resting Heart Rate")
Text("Heart efficiency - optimizes your battery life")
Text("Power Up")
Text("Required to calculate your personal life battery") 